export interface Customer {
  firstName: string
  middleName: string
  lastName: string
  gender: string
  address: string
  city: string
  state: string
  country: string
  dateOfBirth: Date
  email?: string
  phoneNumber: string
  accountNumber: string
}

export interface CustomerDetails {
  firstName: string
  middleName: string
  lastName: string
  gender: string
  address: string
  email?: string
  city: string
  state: string
  country: string
  dateOfBirth: Date
  age: number
  ageGeneration: string
  education: string
  occupation: string
  phoneNumber: string
  maritalStatus: string
  employmentStatus: string
  nationality: string
  religion: string
  socialInstagram: string
  socialTwitter: string
  socialFacebook: string
  personalPreference: string
  motherMaidenName: string
  nextOfKinFirstName: string
  nextOfKinLastName: string
  nextOfKinGender: string
  nextOfKinPhoneNumber: string
  nextOfKinAddress: string
  idNin: string
  idPassport: string
  idLicense: string
  idDriversLicense: string
  onAtc: string
  accountNumber: string
  accountName: string
  openDate: Date
  customerId: number
  branchCode: number
  branchName: string
  productName: string
  productCode: number
  financialSegment: string
  accountOfficerId: string
  accountOfficer: string
  accountOfficerEmail: string
  zmName: string
  zmEmail: string
  bdmName: string
  bdmEmail: string
  regionName: string
  zoneName: string
  clusterName: string
  accountStatus: string
  currencyCode: string
  currencyName: string
  isFrozen: string
  freezeReason: string
  onboardingChannel: string
  clearBalance: number
  cumDrAmount: number
  cumCrAmount: number
  lastTranDateDr: Date
  lastTranDateCr: Date
  onAlat: boolean
  onUssd: boolean
  onAfb: string
  hasCard: boolean
}
